apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: meetup-keda-demo
spec:
  scaleTargetRef:
    name: http-eda-api
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"