apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp-01-demo
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: sampleapp-01-demo
  labels:
    run: api-svc
spec:
  type: LoadBalancer    
  ports:
  - port: 3002
    targetPort: 3000
    protocol: TCP  
  selector:
    run: api-api 
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: product-svc
#   namespace: sampleapp-01-demo
#   labels:
#     run: product-svc
# spec:
#   type: LoadBalancer    
#   ports:
#   - port: 3003
#     targetPort: 3000
#     protocol: TCP  
#   selector:
#     run: product-api 
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: order-svc
#   namespace: sampleapp-01-demo
#   labels:
#     run: order-svc
# spec:
#   type: LoadBalancer    
#   ports:
#   - port: 3003
#     targetPort: 3000
#     protocol: TCP  
#   selector:
#     run: order-api         
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: sampleapp-01-demo
  labels:
    run: mongodb-svc
spec:
  type: LoadBalancer
  ports:
  - port: 28017
    targetPort: 27017    
    protocol: TCP  
  selector:
    run: mongodb
---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: sampleapp-01-demo
data:
  mongodb-username: garrardkitchen
  mongodb-password: mypassword
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: sampleapp-01-demo
spec:
  selector:
    matchLabels:
      run: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb        
    spec:
      containers:
      - name: mongodb        
        image: mongo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 28017
        env:
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mongodb-username           
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mongodb-username       
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mongodb-password                     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api 
  namespace: sampleapp-01-demo
spec:  
  selector:
    matchLabels:
      run: customer-api 
  replicas: 1
  template:
    metadata:
      labels:
        run: customer-api 
    spec:     
      hostname: customer
      containers:
      - name: customer-api        
        image: cf247garrard.azurecr.io/meetup-sampleapp-01-customer-api:latest
        imagePullPolicy: Always      
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mongodb-username           
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mongodb-password                                      
#---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: product-api 
#   namespace: sampleapp-01-demo
# spec:  
#   selector:
#     matchLabels:
#       run: product-api 
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         run: product-api 
#     spec:     
#       hostname: product
#       containers:
#       - name: product-api        
#         image: cf247garrard.azurecr.io/meetup-sampleapp-01-product-api:latest
#         imagePullPolicy: Always      
#         env:
#         - name: MONGODB_USERNAME
#           valueFrom:
#             configMapKeyRef:
#               name: db-config
#               key: mongodb-username           
#         - name: MONGODB_PASSWORD
#           valueFrom:
#             configMapKeyRef:
#               name: db-config
#               key: mongodb-password    
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: product-api 
#   namespace: sampleapp-01-demo
# spec:  
#   selector:
#     matchLabels:
#       run: product-api 
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         run: product-api 
#     spec:     
#       hostname: product
#       containers:
#       - name: product-api        
#         image: cf247garrard.azurecr.io/meetup-sampleapp-01-product-api:latest
#         imagePullPolicy: Always      
#         env:
#         - name: MONGODB_USERNAME
#           valueFrom:
#             configMapKeyRef:
#               name: db-config
#               key: mongodb-username           
#         - name: MONGODB_PASSWORD
#           valueFrom:
#             configMapKeyRef:
#               name: db-config
#               key: mongodb-password                                    