apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: meetup-keda-only-demo
  labels:
    run: mongodb-svc
spec:
  type: LoadBalancer
  ports:
    - port: 28017
      targetPort: 27017
      protocol: TCP
  selector:
    run: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: meetup-keda-only-demo
spec:
  selector:
    matchLabels:
      run: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_USERNAME
              value: garrard
            - name: MONGO_INITDB_ROOT_USERNAME
              value: garrard
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-passwords
                  key: redis-password