apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: meetup-dapr-demo
spec:
  tracing:
    samplingRate: "0"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: meetup-dapr-demo
spec:
  type: exporters.native
  metadata:
    - name: enabled
      value: "true"
    - name: agentEndpoint
      value: "otel-collector.default.svc.cluster.local:55678"
