apiVersion: v1
kind: Namespace
metadata:
  name: meetup-tcp-demo
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: meetup-tcp-demo
  labels:
    run: client-svc
spec:
  type: LoadBalancer    
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP  
  selector:
    run: client
---
apiVersion: v1
kind: Service
metadata:
  name: math-svc
  namespace: meetup-tcp-demo
  labels:
    run: math-svc
spec:
  type: ClusterIP    
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP  
  selector:
    run: math
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math
  namespace: meetup-tcp-demo
spec:  
  selector:
    matchLabels:
      run: math
  replicas: 1
  template:
    metadata:
      labels:
        run: math
    spec:     
      hostname: math
      containers:
      - name: math        
        image: cf247garrard.azurecr.io/meetup-ms-tcp-math:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: meetup-tcp-demo
spec:
  selector:
    matchLabels:
      run: client
  replicas: 1
  template:
    metadata:
      labels:
        run: client
    spec:     
      containers:
      - name: client
        image: cf247garrard.azurecr.io/meetup-ms-tcp-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
             